defaultLeetcodeJson = "leetcode.json"
operationName = "question"
leetcodeCom = "https://leetcode.com"
graphql = "https://leetcode.com/graphql"
problemsAllUrl = "https://leetcode.com/api/problems/all/"
descriptionTemplate = "https://leetcode.com/problems/%v/description/"
solutionTpl = "cmd/solution.tpl.txt"
problemTpl = "cmd/problem.tpl.txt"
readmeTpl = "cmd/readme.tpl.txt"
unittestTpl = "cmd/unittest.tpl.txt"
algorithmsLock = "algorithms.json"